name: PR based CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: execute unit test
        run: |
          chmod +x ./gradlew
          ./gradlew testDebugUnitTest
